version: '3.9'
services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: flight-sqlserver
    ports:
      - 1433:1433
    volumes:
      - mssqlsystem:/var/opt/mssql
      - mssqluser:/var/opt/sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Strong@Passw0rd

  redis:
    image: redis:7.0-alpine
    container_name: flight-redis
    restart: unless-stopped
    command: redis-server --requirepass admin
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: flight-redis-gui
    restart: unless-stopped
    ports:
      - 16379:8001
    volumes:
      - redis-insight-data:/db
    depends_on:
      - redis


volumes:
  redis-data:
    driver: local
  redis-insight-data:
    driver: local
  redis:
    driver: local
  mssqlsystem:
    driver: local
  mssqluser:
    driver: local
